// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodePreset: typeof import('./components/preset/md/CodePreset.md')['default']
    EslintTest: typeof import('./components/preset/EslintTest.vue')['default']
    FeatIndex: typeof import('./components/FeatIndex.vue')['default']
    ReactivityTransform: typeof import('./components/preset/reactivity-transform/reactivityTransform.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestExpose: typeof import('./components/preset/TestExpose.vue')['default']
    WindiCSS: typeof import('./components/preset/WindiCSS/WindiCSS.vue')['default']
  }

}
