/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BuildFeat: typeof import('./components/preset/feat/BuildFeat.vue')['default']
    CodePreset: typeof import('./components/preset/md/CodePreset.md')['default']
    CriteriaFeat: typeof import('./components/preset/feat/CriteriaFeat.vue')['default']
    EslintTest: typeof import('./components/preset/trivial/EslintTest.vue')['default']
    FeatHome: typeof import('./components/preset/FeatHome.vue')['default']
    FeatPage: typeof import('./components/preset/feat/FeatPage.vue')['default']
    LogicFeat: typeof import('./components/preset/feat/LogicFeat.vue')['default']
    ReactivityTransform: typeof import('./components/preset/reactivity-transform/reactivityTransform.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCol: typeof import('tdesign-vue-next')['Col']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TRow: typeof import('tdesign-vue-next')['Row']
  }
}
