// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Code: typeof import('./components/preset/md/code.md')['default']
    EslintTest: typeof import('./components/preset/EslintTest.vue')['default']
    TestExpose: typeof import('./components/preset/TestExpose.vue')['default']
  }

}
